name: Daily Develop to Main Pull Request

on:
  schedule:
    - cron: '0 7 * * *'  # Runs daily at 7:00 AM UTC
permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Check for differences
        id: check_diff
        run: |
          git fetch origin develop main
          DIFF=$(git rev-list --count main..develop)
          echo "DIFF_COUNT=$DIFF" >> $GITHUB_ENV
          echo "Número de commits diferentes: $DIFF"
          
      - name: Crear Pull Request
        if: env.DIFF_COUNT != '0'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const headBranch = 'develop';
            const baseBranch = 'main';

            const { data: existingPRs } = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open',
              head: `${owner}:${headBranch}`,
              base: baseBranch,
            });

            if (existingPRs.length === 0) {
              const { data: newPR } = await github.rest.pulls.create({
                owner,
                repo,
                title: 'Actualización semanal: develop a main',
                head: headBranch,
                base: baseBranch,
                body: 'Pull request automatizada para sincronizar cambios de develop a main.',
              });

              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: newPR.number,
                labels: ['automated-pr'],
              });

              console.log(`✅ Pull request creada: ${newPR.html_url}`);
            } else {
              console.log('🔄 Ya existe una pull request abierta de develop a main.');
            }
      
      - name: No changes found
        if: env.DIFF_COUNT == '0'
        run: echo "No hay cambios entre develop y main. No se creará un PR."
