name: Daily Develop to Main Pull Request

on:
  schedule:
    - cron: '36 07 * * 4'  # Every Thursday at 09:30 Spanish Summer Time (CEST/UTC+2)
  
permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Crear Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const headBranch = 'develop';
            const baseBranch = 'main';

            // Verificar si ya existe una pull request abierta desde 'develop' a 'main'
            const { data: existingPRs } = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open',
              head: `${owner}:${headBranch}`,
              base: baseBranch,
            });

            if (existingPRs.length === 0) {
              // Crear una nueva pull request
              const { data: newPR } = await github.rest.pulls.create({
                owner,
                repo,
                title: 'Actualización diaria: develop a main',
                head: headBranch,
                base: baseBranch,
                body: 'Esta pull request se ha creado automáticamente para sincronizar los cambios de develop a main.',
              });

              // Agregar etiquetas a la pull request 
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: newPR.number,
                labels: ['automated-pr'],
              });

              console.log(`Pull request creada: ${newPR.html_url}`);
            } else {
              console.log('Ya existe una pull request abierta de develop a main.');
            }